# Generated by Django 5.0.6 on 2024-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='other_dojo',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dojo',
            field=models.CharField(max_length=100, verbose_name='Dojo'),
        ),
    ]
