# Generated by Django 5.0.6 on 2024-07-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='The email address of the participant.', max_length=254, null=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, help_text='The first name of the participant.', max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='The last name of the participant.', max_length=100, null=True, verbose_name='Last Name')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the participant registered for the course.', verbose_name='Registration date')),
                ('dojo', models.CharField(blank=True, choices=[('AAR', 'Aikido am Rhein'), ('AVE', 'Aikido Verein Emmendingen'), ('AVF', 'Aikido Verein Freiburg'), ('TVD', 'Turnverein Denzlingen'), ('other', 'Other Dojo')], help_text='The dojo the participant belongs to.', max_length=5, null=True, verbose_name='Dojo')),
                ('other_dojo', models.CharField(blank=True, help_text="The name of the participant's Dojo outside of D.A.N. BW.", max_length=100, verbose_name='Other Dojo')),
                ('grade', models.IntegerField(blank=True, choices=[(0, 'Red Belt 🔴'), (1, '6th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤'), (7, '1st Dan ⚫️'), (8, '2nd  Dan ⚫️'), (9, '3rd Dan ⚫️'), (10, '4th Dan ⚫️'), (11, '5th Dan ⚫️'), (12, '6th Dan ⚫️')], default=0, help_text='The grade of the participant.', null=True, verbose_name='Grade')),
                ('exam', models.BooleanField(default=False, help_text='Indicates whether the participant would like to take an exam.', verbose_name='Exam')),
                ('exam_grade', models.IntegerField(blank=True, choices=[(1, '6th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤')], help_text='The grade of the exam the participant would like to take.', null=True, verbose_name='Exam Grade')),
                ('exam_passed', models.BooleanField(null=True, verbose_name='Exam Passed')),
                ('grade_updated', models.BooleanField(default=False, verbose_name='Grade Updated')),
                ('accept_terms', models.BooleanField(default=False, help_text='Indicates whether the participant has accepted the terms and conditions.', verbose_name='Accept terms')),
                ('discount', models.BooleanField(default=False, help_text='Indicates whether the participant is eligible for a discount.', verbose_name='Discount')),
                ('final_fee', models.IntegerField(default=0, help_text='The final fee the participant needs to pay.', verbose_name='Final Fee')),
                ('payment_status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0, help_text="The status of the participant's payment for the course.", verbose_name='Payment status')),
                ('payment_method', models.IntegerField(choices=[(0, 'Bank Transfer'), (1, 'Cash')], default=0, help_text='The method by which the participant will make the payment.', verbose_name='Payment method')),
                ('comment', models.TextField(blank=True, help_text='Any additional comments or notes regarding the registration.', verbose_name='Comment')),
                ('dinner', models.BooleanField(blank=True, help_text='Indicates whether the participant will attend the dinner.', null=True, verbose_name='Dinner')),
                ('overnight_stay', models.BooleanField(blank=True, help_text='Indicates whether the participant needs a place to stay overnight.', null=True, verbose_name='Overnight stay')),
                ('course', models.ForeignKey(help_text='The course for which the participant is registering.', on_delete=django.db.models.deletion.CASCADE, to='courses.internalcourse', verbose_name='Course')),
                ('selected_sessions', models.ManyToManyField(help_text='The sessions within the course that the participant has selected.', to='courses.coursesession', verbose_name='Selected sessions')),
                ('user', models.ForeignKey(blank=True, help_text='The user who is registering for the course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Course Registration',
                'verbose_name_plural': 'Course Registrations',
            },
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'course'), name='unique_user_registration'),
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email', 'course'), name='unique_guest_registration'),
        ),
    ]
