# Generated by Django 5.0.6 on 2024-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='other_dojo',
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='dojo',
            field=models.CharField(blank=True, help_text='The dojo the participant belongs to.', max_length=100, null=True, verbose_name='Dojo'),
        ),
    ]
