# Generated by Django 5.0.6 on 2024-09-11 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0002_remove_courseregistration_other_dojo_and_more'),
        ('courses', '0003_alter_course_end_date_alter_course_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='Accept terms'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.internalcourse', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='dinner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Dinner'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='dojo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dojo'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='exam',
            field=models.BooleanField(default=False, null=True, verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='exam_grade',
            field=models.IntegerField(blank=True, choices=[(1, '6th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤')], null=True, verbose_name='Exam Grade'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='final_fee',
            field=models.IntegerField(default=0, verbose_name='Final Fee'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(0, 'Red Belt 🔴'), (1, '6th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤'), (7, '1st Dan ⚫️'), (8, '2nd  Dan ⚫️'), (9, '3rd Dan ⚫️'), (10, '4th Dan ⚫️'), (11, '5th Dan ⚫️'), (12, '6th Dan ⚫️')], default=0, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='overnight_stay',
            field=models.BooleanField(blank=True, null=True, verbose_name='Overnight stay'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Bank Transfer'), (1, 'Cash')], default=0, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0, verbose_name='Payment status'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='selected_sessions',
            field=models.ManyToManyField(to='courses.coursesession', verbose_name='Selected sessions'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
    ]
