# Generated by Django 5.0.6 on 2024-10-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0003_alter_courseregistration_accept_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='attended',
            field=models.BooleanField(default=True, verbose_name='Attended'),
        ),
    ]
