# Generated by Django 5.0.6 on 2024-10-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0004_courseregistration_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='attended',
            field=models.BooleanField(default=True, null=True, verbose_name='Attended'),
        ),
    ]
