# Generated by Django 5.0.6 on 2025-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0005_alter_courseregistration_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='dan_member',
            field=models.BooleanField(default=False, verbose_name='D.A.N. Member'),
        ),
    ]
