# Generated by Django 5.0.6 on 2025-01-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0006_courseregistration_dan_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='final_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Final Fee'),
        ),
    ]
