# Generated by Django 5.0.6 on 2025-12-07 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0007_alter_courseregistration_final_fee'),
        ('courses', '0009_alter_coursesession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseregistration',
            name='unique_guest_registration',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='accommodation_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.accommodationoption', verbose_name='Accommodation Option'),
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email', 'first_name', 'last_name', 'course'), name='unique_guest_registration'),
        ),
    ]
