# Generated by Django 5.0.6 on 2026-03-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0008_remove_courseregistration_unique_guest_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='deposit_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Amount of deposit received from the participant. See 'Remaining Balance' below.", max_digits=10, null=True, verbose_name='Deposit Paid'),
        ),
    ]
