# Generated by Django 5.2.14 on 2026-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_registrations", "0009_courseregistration_deposit_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseregistration",
            name="anonymized_on",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Anonymized on"
            ),
        ),
    ]
