# Generated by Django 4.2.3 on 2024-04-26 12:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('menu_position', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['menu_position'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('teacher', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_fee', models.IntegerField(default=0)),
                ('session_fee_cash', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_registration.course')),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField()),
            ],
            bases=('course_registration.course',),
        ),
        migrations.CreateModel(
            name='InternalCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_registration.course')),
                ('registration_status', models.IntegerField(choices=[(0, 'Closed'), (1, 'Open')], default=0)),
                ('description', models.TextField(blank=True)),
                ('registration_start_date', models.DateField(blank=True)),
                ('registration_end_date', models.DateField(blank=True)),
                ('organizer', models.CharField(blank=True, default='DANBW', max_length=200)),
                ('course_fee', models.IntegerField()),
                ('course_fee_cash', models.IntegerField()),
                ('discount_percentage', models.IntegerField(default=50)),
                ('bank_transfer_until', models.DateField()),
            ],
            bases=('course_registration.course',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('content', models.TextField()),
                ('menu_position', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='course_registration.category')),
            ],
            options={
                'ordering': ['menu_position'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('exam', models.BooleanField(default=False)),
                ('exam_grade', models.IntegerField(choices=[(1, '7th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤')], default=0)),
                ('exam_passed', models.BooleanField(null=True)),
                ('grade_updated', models.BooleanField(default=False)),
                ('accept_terms', models.BooleanField(default=False)),
                ('discount', models.BooleanField(default=False)),
                ('final_fee', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
                ('payment_method', models.IntegerField(choices=[(0, 'Bank Transfer'), (1, 'Cash')], default=0)),
                ('comment', models.TextField(blank=True)),
                ('selected_sessions', models.ManyToManyField(to='course_registration.coursesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.internalcourse')),
            ],
        ),
        migrations.CreateModel(
            name='GuestCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('dojo', models.CharField(choices=[('AAR', 'Aikido am Rhein'), ('AVE', 'Aikido Verein Emmendingen'), ('AVF', 'Aikido Verein Freiburg'), ('TVD', 'Turnverein Denzlingen')], max_length=3)),
                ('grade', models.IntegerField(choices=[(0, 'Red Belt 🔴'), (1, '6th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤'), (7, '1st Dan ⚫️'), (8, '2nd  Dan ⚫️'), (9, '3rd Dan ⚫️'), (10, '4th Dan ⚫️'), (11, '5th Dan ⚫️'), (12, '6th Dan ⚫️')], default=0)),
                ('exam', models.BooleanField(default=False)),
                ('exam_grade', models.IntegerField(blank=True, choices=[(1, '7th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤')], null=True)),
                ('accept_terms', models.BooleanField(default=False)),
                ('discount', models.BooleanField(default=False)),
                ('final_fee', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
                ('payment_method', models.IntegerField(choices=[(0, 'Bank Transfer'), (1, 'Cash')], default=0)),
                ('comment', models.TextField(blank=True)),
                ('selected_sessions', models.ManyToManyField(to='course_registration.coursesession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.internalcourse')),
            ],
        ),
        migrations.AddField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course_registration.internalcourse'),
        ),
        migrations.AddConstraint(
            model_name='usercourseregistration',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_registration'),
        ),
        migrations.AddConstraint(
            model_name='guestcourseregistration',
            constraint=models.UniqueConstraint(fields=('email', 'course'), name='unique_guest_registration'),
        ),
    ]
