# Generated by Django 4.2.3 on 2023-07-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "registration_status",
                    models.IntegerField(
                        choices=[(0, "Closed"), (1, "Open")], default=0
                    ),
                ),
                ("course_fee", models.IntegerField()),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
