# Generated by Django 4.2.3 on 2023-07-05 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("session_fee", models.IntegerField(default=10)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_registration.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("exam", models.BooleanField(default=False)),
                ("accept_terms", models.BooleanField(default=False)),
                ("final_fee", models.IntegerField()),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[(0, "Unpaid"), (1, "Paid")], default=0
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_registration.course",
                    ),
                ),
                (
                    "course_sessions",
                    models.ManyToManyField(to="course_registration.coursesession"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="courseregistration",
            constraint=models.UniqueConstraint(
                fields=("user", "course"), name="unique_user_registration"
            ),
        ),
    ]
