# Generated by Django 4.2.3 on 2023-07-07 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0002_coursesession_courseregistration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseregistration",
            old_name="course_sessions",
            new_name="selected_sessions",
        ),
    ]
