# Generated by Django 4.2.3 on 2023-07-07 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_registration", "0005_customuser_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("ng", "No Grade (Red Belt)"),
                            ("6k", "6. Kyu (White Belt)"),
                            ("5k", "5. Kyu (Yellow Belt)"),
                            ("4k", "4. Kyu (Orange Belt)"),
                            ("3k", "3. Kyu (Green Belt)"),
                            ("2k", "2. Kyu (Blue Belt)"),
                            ("1k", "1. Kyu (Brown Belt)"),
                            ("1d", "1. Dan"),
                            ("2d", "2. Dan"),
                            ("3d", "3. Dan"),
                            ("4d", "4. Dan"),
                            ("5d", "5. Dan"),
                            ("6d", "6. Dan"),
                        ],
                        default="ng",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
