# Generated by Django 4.2.3 on 2023-07-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0008_remove_userprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
