# Generated by Django 4.2.3 on 2023-07-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0010_remove_userprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(default=10, unique=True),
            preserve_default=False,
        ),
    ]
