# Generated by Django 4.2.3 on 2023-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0011_userprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="First name", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(default="Last name", max_length=200),
            preserve_default=False,
        ),
    ]
