# Generated by Django 4.2.3 on 2023-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0013_remove_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="grade",
            field=models.CharField(
                choices=[
                    ("ng", "No Grade 🔴"),
                    ("6k", "6th Kyu ⚪️"),
                    ("5k", "5th Kyu 🟡"),
                    ("4k", "4th Kyu 🟠"),
                    ("3k", "3rd Kyu 🟢"),
                    ("2k", "2nd Kyu 🔵"),
                    ("1k", "1st Kyu 🟤"),
                    ("1d", "1st Dan ⚫️"),
                    ("2d", "2nd  Dan ⚫️"),
                    ("3d", "3rd Dan ⚫️"),
                    ("4d", "4th Dan ⚫️"),
                    ("5d", "5th Dan ⚫️"),
                    ("6d", "6th Dan ⚫️"),
                ],
                default="ng",
                max_length=2,
            ),
        ),
    ]
