# Generated by Django 4.2.3 on 2023-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0018_rename_grade_courseregistration_exam_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseregistration",
            name="exam_passed",
            field=models.BooleanField(default=False),
        ),
    ]
