# Generated by Django 4.2.3 on 2023-07-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0021_alter_courseregistration_exam_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseregistration",
            name="exam_grade",
            field=models.IntegerField(
                choices=[
                    (0, "Red Belt 🔴"),
                    (1, "6th Kyu ⚪️"),
                    (2, "5th Kyu 🟡"),
                    (3, "4th Kyu 🟠"),
                    (4, "3rd Kyu 🟢"),
                    (5, "2nd Kyu 🔵"),
                ],
                default=0,
            ),
        ),
    ]
