# Generated by Django 4.2.3 on 2023-07-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0023_alter_courseregistration_exam_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseregistration",
            name="exam_passed",
            field=models.BooleanField(null=True),
        ),
    ]
