# Generated by Django 4.2.3 on 2023-07-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0024_alter_courseregistration_exam_passed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseregistration",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_registrations",
                to="course_registration.course",
            ),
        ),
        migrations.AlterField(
            model_name="coursesession",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_sessions",
                to="course_registration.course",
            ),
        ),
    ]
