# Generated by Django 4.2.3 on 2023-07-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0025_alter_courseregistration_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseregistration",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_registration.course",
            ),
        ),
        migrations.AlterField(
            model_name="courseregistration",
            name="final_fee",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coursesession",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="course_registration.course",
            ),
        ),
    ]
