# Generated by Django 4.2.3 on 2023-07-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0027_category_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(default="slug", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
