# Generated by Django 4.2.3 on 2023-07-21 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0028_page_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
