# Generated by Django 4.2.3 on 2023-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_registration", "0029_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="slug", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
