# Generated by Django 4.2.3 on 2023-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0033_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_index']},
        ),
        migrations.AddField(
            model_name='page',
            name='menu_index',
            field=models.IntegerField(default=0),
        ),
    ]
