# Generated by Django 4.2.3 on 2023-08-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0035_alter_page_options_remove_page_menu_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_index']},
        ),
        migrations.AddField(
            model_name='page',
            name='menu_index',
            field=models.IntegerField(default=0),
        ),
    ]
