# Generated by Django 4.2.3 on 2023-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0036_alter_page_options_page_menu_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['menu_index'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='menu_index',
            field=models.IntegerField(default=0),
        ),
    ]
