# Generated by Django 4.2.3 on 2023-08-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0037_alter_category_options_category_menu_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['menu_position'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_position']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='menu_index',
            new_name='menu_position',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='menu_index',
            new_name='menu_position',
        ),
    ]
