# Generated by Django 4.2.3 on 2024-04-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0039_alter_courseregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
