# Generated by Django 4.2.3 on 2024-04-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0040_course_organizer_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_registration.course')),
                ('url', models.URLField()),
            ],
            bases=('course_registration.course',),
        ),
        migrations.CreateModel(
            name='GuestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='registration_status',
        ),
        migrations.CreateModel(
            name='InternalCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_registration.course')),
                ('registration_status', models.IntegerField(choices=[(0, 'Closed'), (1, 'Open')], default=0)),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('course_fee', models.IntegerField()),
                ('course_fee_cash', models.IntegerField()),
            ],
            bases=('course_registration.course',),
        ),
    ]
