# Generated by Django 4.2.3 on 2024-04-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0042_remove_course_description_internalcourse_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestRegistration',
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.internalcourse'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course_registration.internalcourse'),
        ),
    ]
