# Generated by Django 4.2.3 on 2024-04-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0043_delete_guestregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcourse',
            name='registration_end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='registration_start_date',
            field=models.DateField(blank=True),
        ),
    ]
