# Generated by Django 4.2.3 on 2024-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0044_alter_internalcourse_registration_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='organizer',
        ),
        migrations.AddField(
            model_name='externalcourse',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
