# Generated by Django 4.2.3 on 2024-04-17 20:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_registration', '0046_internalcourse_organizer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRegistration',
            new_name='UserCourseRegistration',
        ),
    ]
