# Generated by Django 4.2.3 on 2024-04-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0047_rename_courseregistration_usercourseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('accept_terms', models.BooleanField(default=False)),
                ('final_fee', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
                ('comment', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.internalcourse')),
                ('selected_sessions', models.ManyToManyField(to='course_registration.coursesession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='guestcourseregistration',
            constraint=models.UniqueConstraint(fields=('email', 'course'), name='unique_guest_registration'),
        ),
    ]
