# Generated by Django 4.2.3 on 2024-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0051_guestcourseregistration_exam_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcourseregistration',
            name='dojo',
            field=models.CharField(choices=[('AAR', 'Aikido am Rhein'), ('AVE', 'Aikido Verein Emmendingen'), ('AVF', 'Aikido Verein Freiburg'), ('TVD', 'Turnverein Denzlingen')], default='AVF', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dojo',
            field=models.CharField(choices=[('AAR', 'Aikido am Rhein'), ('AVE', 'Aikido Verein Emmendingen'), ('AVF', 'Aikido Verein Freiburg'), ('TVD', 'Turnverein Denzlingen')], default='AVF', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestcourseregistration',
            name='exam_grade',
            field=models.IntegerField(choices=[(1, '7th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤')]),
        ),
    ]
