# Generated by Django 4.2.3 on 2024-04-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0052_guestcourseregistration_dojo_userprofile_dojo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcourseregistration',
            name='exam_grade',
            field=models.IntegerField(blank=True, choices=[(1, '7th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤')]),
        ),
    ]
