# Generated by Django 4.2.3 on 2024-04-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0054_alter_guestcourseregistration_exam_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcourse',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
