# Generated by Django 4.2.3 on 2024-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0055_internalcourse_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcourseregistration',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseregistration',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
