# Generated by Django 4.2.3 on 2024-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0056_guestcourseregistration_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcourse',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='internalcourse',
            name='discount_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
