# Generated by Django 4.2.3 on 2024-04-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0057_remove_internalcourse_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcourse',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
