# Generated by Django 4.2.3 on 2024-04-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0059_alter_internalcourse_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcourseregistration',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer')], default=0),
        ),
        migrations.AddField(
            model_name='usercourseregistration',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer')], default=0),
        ),
    ]
