# Generated by Django 4.2.3 on 2024-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0060_guestcourseregistration_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='session_fee_cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='session_fee',
            field=models.IntegerField(default=0),
        ),
    ]
