# Generated by Django 4.2.3 on 2024-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0061_coursesession_session_fee_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcourse',
            name='discount_rate',
        ),
        migrations.AddField(
            model_name='internalcourse',
            name='discount_percentage',
            field=models.IntegerField(default=100),
        ),
    ]
