# Generated by Django 4.2.3 on 2024-04-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0063_alter_guestcourseregistration_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcourse',
            name='discount_percentage',
            field=models.IntegerField(default=50, verbose_name='Discount in %'),
        ),
    ]
