# Generated by Django 4.2.3 on 2024-04-24 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0066_rename_bank_transfer_deadline_internalcourse_bank_transfer_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(7, 0), '7:00 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(21, 0), '9:00 pm')]),
        ),
    ]
