# Generated by Django 4.2.3 on 2024-04-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0067_alter_coursesession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
