# Generated by Django 5.0.6 on 2025-01-23 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('sensei_emmerson', 'Sensei Emmerson'), ('hombu_dojo', 'Hombu Dojo Instructor'), ('external_teacher', 'External Teacher'), ('dan_bw_teacher', 'D.A.N. BW Teacher'), ('children', 'Children')], max_length=50, verbose_name='Course Type')),
                ('fee_category', models.CharField(blank=True, choices=[('regular', 'Regular Course'), ('dan_seminar', 'Dan Seminar')], max_length=50, null=True, verbose_name='Fee Category')),
                ('fee_type', models.CharField(choices=[('single_session', 'Single Session'), ('entire_course', 'Entire Course'), ('single_day', 'Single Day'), ('single_session_dan_preparation', 'Dan Preparation Session'), ('entire_course_dan_preparation', 'Entire Course with Dan Preparation')], max_length=50, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('extra_fee_external', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Extra Fee External')),
                ('extra_fee_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Extra Fee Cash')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
                'unique_together': {('course_type', 'fee_category', 'fee_type')},
            },
        ),
    ]
