# Generated by Django 5.0.6 on 2025-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='course_type',
            field=models.CharField(choices=[('sensei_emmerson', 'Sensei Emmerson'), ('hombu_dojo', 'Hombu Dojo Instructor'), ('external_teacher', 'External Teacher'), ('dan_bw_teacher', 'D.A.N. BW Teacher'), ('children', 'Children'), ('family_reunion', 'Family Reunion')], max_length=50, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_category',
            field=models.CharField(blank=True, choices=[('regular', 'Regular Course'), ('dan_seminar', 'Dan Seminar'), ('family_reunion', 'Family Reunion')], max_length=50, null=True, verbose_name='Fee Category'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('single_session', 'Single Session'), ('entire_course', 'Entire Course'), ('single_day', 'Single Day'), ('single_session_dan_preparation', 'Dan Preparation Session'), ('entire_course_dan_preparation', 'Entire Course with Dan Preparation'), ('single_day_with_dan_seminar', 'Single Day with Dan Seminar'), ('entire_course_with_dan_seminar', 'Entire Course with Dan Seminar')], max_length=50, verbose_name='Fee Type'),
        ),
    ]
