# Generated by Django 5.0.6 on 2026-03-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_fee_course_type_alter_fee_fee_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='course_type',
            field=models.CharField(choices=[('sensei_emmerson', 'Sensei Emmerson'), ('hombu_dojo', 'Hombu Dojo Instructor'), ('external_teacher', 'External Teacher'), ('dan_bw_teacher', 'D.A.N. BW Teacher'), ('children', 'Children'), ('family_reunion', 'Family Reunion'), ('other', 'Other Course')], max_length=50, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_category',
            field=models.CharField(blank=True, choices=[('regular', 'Regular Course'), ('dan_seminar', 'Dan Seminar'), ('family_reunion', 'Family Reunion'), ('other', 'Other Course')], max_length=50, null=True, verbose_name='Fee Category'),
        ),
    ]
