# Generated by Django 5.0.6 on 2024-07-29 16:03

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('menu_position', models.IntegerField(default=0, verbose_name='menu position')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['menu_position'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the page', max_length=200, unique=True, verbose_name='title')),
                ('slug', models.SlugField(help_text='The URL of the page', max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='The status of the page (published or draft)', verbose_name='status')),
                ('featured_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='placeholder', help_text='The featured image of the page', upload_to='images/', verbose_name='featured image')),
                ('content', models.TextField(help_text='The page content', verbose_name='content')),
                ('menu_position', models.IntegerField(default=0, help_text='The position in the menu (lower numbers appear first)', verbose_name='menu position')),
                ('category', models.ForeignKey(help_text='The category of the page (determines the menu position)', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['menu_position'],
            },
        ),
    ]
