# Generated by Django 5.0.6 on 2024-09-11 20:39

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='featured_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='placeholder', upload_to='images/', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='menu_position',
            field=models.IntegerField(default=0, verbose_name='menu position'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='title'),
        ),
    ]
