# Generated by Django 5.0.6 on 2026-03-02 13:44

import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'category Translation'},
        ),
        migrations.AlterModelOptions(
            name='pagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'page Translation'},
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.category'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
