# Generated by Django 5.2.14 on 2026-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_categorytranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pagetranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='pages_category_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='pagetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='pages_page_translation_uniq_lang'),
        ),
    ]
