# Generated by Django 5.0.6 on 2024-07-29 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrensPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('street_number', models.CharField(max_length=10, verbose_name='Street Number')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_postcode', message='Enter a valid postcode.', regex='^[0-9]{1,10}$')], verbose_name='Postcode')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_home', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Home Phone')),
                ('phone_mobile', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Phone')),
                ('grade', models.IntegerField(choices=[(0, 'Red Belt 🔴'), (1, '6th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤'), (7, '1st Dan ⚫️'), (8, '2nd  Dan ⚫️'), (9, '3rd Dan ⚫️'), (10, '4th Dan ⚫️'), (11, '5th Dan ⚫️'), (12, '6th Dan ⚫️')], verbose_name='Grade')),
                ('dojo', models.CharField(choices=[('AAR', 'Aikido am Rhein'), ('AVE', 'Aikido Verein Emmendingen'), ('AVF', 'Aikido Verein Freiburg'), ('TVD', 'Turnverein Denzlingen'), ('other', 'Other Dojo')], max_length=100, verbose_name='Dojo')),
                ('other_dojo', models.CharField(blank=True, max_length=100, verbose_name='Other Dojo')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Accept Terms')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('name_legal_guardian', models.CharField(max_length=100, verbose_name='Name of Legal Guardian')),
                ('liability_disclaimer', models.BooleanField(default=False, verbose_name='Liability Disclaimer')),
                ('passport_issued', models.BooleanField(default=False, verbose_name='Passport Issued')),
            ],
            options={
                'verbose_name': 'Childrens Passport',
                'verbose_name_plural': 'Childrens Passports',
            },
        ),
        migrations.CreateModel(
            name='DanBwMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('street_number', models.CharField(max_length=10, verbose_name='Street Number')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_postcode', message='Enter a valid postcode.', regex='^[0-9]{1,10}$')], verbose_name='Postcode')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_home', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Home Phone')),
                ('phone_mobile', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Phone')),
                ('grade', models.IntegerField(choices=[(0, 'Red Belt 🔴'), (1, '6th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤'), (7, '1st Dan ⚫️'), (8, '2nd  Dan ⚫️'), (9, '3rd Dan ⚫️'), (10, '4th Dan ⚫️'), (11, '5th Dan ⚫️'), (12, '6th Dan ⚫️')], verbose_name='Grade')),
                ('dojo', models.CharField(choices=[('AAR', 'Aikido am Rhein'), ('AVE', 'Aikido Verein Emmendingen'), ('AVF', 'Aikido Verein Freiburg'), ('TVD', 'Turnverein Denzlingen'), ('other', 'Other Dojo')], max_length=100, verbose_name='Dojo')),
                ('other_dojo', models.CharField(blank=True, max_length=100, verbose_name='Other Dojo')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Accept Terms')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'D.A.N. BW Membership',
                'verbose_name_plural': 'D.A.N. BW Memberships',
            },
        ),
        migrations.CreateModel(
            name='DanIntMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('street_number', models.CharField(max_length=10, verbose_name='Street Number')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_postcode', message='Enter a valid postcode.', regex='^[0-9]{1,10}$')], verbose_name='Postcode')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_home', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Home Phone')),
                ('phone_mobile', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Phone')),
                ('grade', models.IntegerField(choices=[(0, 'Red Belt 🔴'), (1, '6th Kyu ⚪️'), (2, '5th Kyu 🟡'), (3, '4th Kyu 🟠'), (4, '3rd Kyu 🟢'), (5, '2nd Kyu 🔵'), (6, '1st Kyu 🟤'), (7, '1st Dan ⚫️'), (8, '2nd  Dan ⚫️'), (9, '3rd Dan ⚫️'), (10, '4th Dan ⚫️'), (11, '5th Dan ⚫️'), (12, '6th Dan ⚫️')], verbose_name='Grade')),
                ('dojo', models.CharField(choices=[('AAR', 'Aikido am Rhein'), ('AVE', 'Aikido Verein Emmendingen'), ('AVF', 'Aikido Verein Freiburg'), ('TVD', 'Turnverein Denzlingen'), ('other', 'Other Dojo')], max_length=100, verbose_name='Dojo')),
                ('other_dojo', models.CharField(blank=True, max_length=100, verbose_name='Other Dojo')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Accept Terms')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('sepa', models.BooleanField(default=False, verbose_name='SEPA Mandate')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Account Holder')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('liability_disclaimer', models.BooleanField(default=False, verbose_name='Liability Disclaimer')),
                ('passport_issued', models.BooleanField(default=False, verbose_name='Passport Issued')),
            ],
            options={
                'verbose_name': 'D.A.N. International Membership',
                'verbose_name_plural': 'D.A.N. International Memberships',
            },
        ),
    ]
