# Generated by Django 5.0.6 on 2024-07-29 16:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the course.', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('start_date', models.DateField(default=datetime.date.today, help_text='The start date of the course.', verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.date.today, help_text='The end date of the course.', verbose_name='End Date')),
                ('teacher', models.CharField(blank=True, help_text='The teacher(s) of the course (optional).', max_length=200, verbose_name='Teacher(s)')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('organizer', models.CharField(blank=True, help_text='The organizer of the course (optional).', max_length=200, verbose_name='Organizer')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'External Course',
                'verbose_name_plural': 'External Courses',
            },
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='InternalCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('status', models.IntegerField(choices=[(0, 'Preview'), (1, 'Published')], default=0, help_text="Courses set to 'Preview' will appear in the course list without all details.", verbose_name='Status')),
                ('publication_date', models.DateField(blank=True, help_text="If this date is set, the course will automatically be set to 'Published' on this date.", null=True, verbose_name='Publication Date')),
                ('registration_status', models.IntegerField(choices=[(0, 'closed'), (1, 'open')], default=0, help_text="If the registration status is set to 'open', users can sign up for the course.", verbose_name='Registration Status')),
                ('description', models.TextField(blank=True, help_text='A short description of the course (optional).', verbose_name='Description')),
                ('location', models.CharField(blank=True, help_text='The location of the course (optional).', max_length=200, verbose_name='Location')),
                ('registration_start_date', models.DateField(blank=True, help_text="If this date is set, the registration status will be automatically set to 'open' on this date.", null=True, verbose_name='Registration Start Date')),
                ('registration_end_date', models.DateField(blank=True, help_text="If this date is set, the registration status will be automatically set to 'closed' on this date.", null=True, verbose_name='Registration End Date')),
                ('organizer', models.CharField(blank=True, default='D.A.N. BW', help_text='The organizer of the course (optional).', max_length=200, verbose_name='Organizer')),
                ('course_fee', models.IntegerField(default=0, help_text='The fee for the entire course (payments via bank transfer).', verbose_name='Course Fee')),
                ('course_fee_cash', models.IntegerField(default=0, help_text='The fee for the entire course (cash payments).', verbose_name='Course Fee (Cash)')),
                ('discount_percentage', models.IntegerField(default=50, help_text='The discount percentage specified here will automatically be applied for users eligible for a discount.', verbose_name='Discount Percentage')),
                ('bank_transfer_until', models.DateField(default=datetime.date.today, help_text='The date until which the course fee has to be paid via bank transfer.', verbose_name='Bank Transfer Until')),
                ('course_type', models.CharField(choices=[('regional', 'Regional Course'), ('international', 'International Course'), ('family_reunion', 'Family Reunion')], help_text='The type of the course will determine which fields will be displayed in the registration form.', max_length=200, verbose_name='Course Type')),
                ('flyer', models.ImageField(blank=True, help_text='The course flyer. Needs to be uploaded as an image file (JPEG, PNG, etc.).', null=True, upload_to='images/', verbose_name='Flyer')),
                ('additional_info', models.TextField(blank=True, help_text='Additional information about the course (optional).', verbose_name='Additional Information')),
            ],
            options={
                'verbose_name': 'Internal Course',
                'verbose_name_plural': 'Internal Courses',
            },
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the session.', max_length=200, verbose_name='Title')),
                ('date', models.DateField(default=datetime.date.today, help_text='The date on which the session takes place.', verbose_name='Date')),
                ('start_time', models.TimeField(default='00:00', help_text='The time at which the session starts.', verbose_name='Start Time')),
                ('end_time', models.TimeField(default='00:00', help_text='The time at which the session ends.', verbose_name='End Time')),
                ('session_fee', models.IntegerField(default=0, help_text='The fee for attending this session if paid via bank transfer.', verbose_name='Session Fee')),
                ('session_fee_cash', models.IntegerField(default=0, help_text='The fee for attending this session if paid in cash.', verbose_name='Session Fee (Cash)')),
                ('course', models.ForeignKey(help_text='The course to which this session belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.internalcourse', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Session',
                'verbose_name_plural': 'Course Sessions',
            },
        ),
    ]
