# Generated by Django 5.0.6 on 2024-09-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcourse',
            name='url',
            field=models.URLField(blank=True, help_text='The URL of the course.', verbose_name='URL'),
        ),
    ]
