# Generated by Django 5.0.6 on 2024-09-11 20:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_externalcourse_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=200, verbose_name='Teacher(s)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.internalcourse', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='end_time',
            field=models.TimeField(default='00:00', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='session_fee',
            field=models.IntegerField(default=0, verbose_name='Session Fee'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='session_fee_cash',
            field=models.IntegerField(default=0, verbose_name='Session Fee (Cash)'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='start_time',
            field=models.TimeField(default='00:00', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='externalcourse',
            name='organizer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organizer'),
        ),
        migrations.AlterField(
            model_name='externalcourse',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='bank_transfer_until',
            field=models.DateField(default=datetime.date.today, verbose_name='Bank Transfer Until'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='course_fee',
            field=models.IntegerField(default=0, verbose_name='Course Fee'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='course_fee_cash',
            field=models.IntegerField(default=0, verbose_name='Course Fee (Cash)'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='course_type',
            field=models.CharField(choices=[('regional', 'Regional Course'), ('international', 'International Course'), ('family_reunion', 'Family Reunion'), ('dan_preparation_seminar', 'Dan Preparation/Dan Seminar')], max_length=100, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='discount_percentage',
            field=models.IntegerField(default=50, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Flyer'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='organizer',
            field=models.CharField(blank=True, default='D.A.N. BW', max_length=200, verbose_name='Organizer'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration End Date'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Start Date'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='registration_status',
            field=models.IntegerField(choices=[(0, 'closed'), (1, 'open')], default=0, verbose_name='Registration Status'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='status',
            field=models.IntegerField(choices=[(0, 'Preview'), (1, 'Published')], default=0, verbose_name='Status'),
        ),
    ]
