# Generated by Django 5.0.6 on 2024-09-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_end_date_alter_course_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='is_dan_preparation',
            field=models.BooleanField(default=False, verbose_name='Dan Preparation'),
        ),
        migrations.AddField(
            model_name='internalcourse',
            name='course_fee_with_dan_preparation',
            field=models.IntegerField(blank=True, default=0, verbose_name='Course Fee with Dan Preparation'),
        ),
        migrations.AddField(
            model_name='internalcourse',
            name='course_fee_with_dan_preparation_cash',
            field=models.IntegerField(blank=True, default=0, verbose_name='Course Fee with Dan Preparation (Cash)'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='course_type',
            field=models.CharField(choices=[('specialized', 'Specialized Course'), ('dan_preparation_seminar', 'Dan Preparation/Dan Seminar'), ('international', 'International Course'), ('family_reunion', 'Family Reunion')], max_length=100, verbose_name='Course Type'),
        ),
    ]
