# Generated by Django 5.0.6 on 2024-11-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesession_is_dan_preparation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcourse',
            name='course_type',
            field=models.CharField(choices=[('specialized', 'Specialized Course'), ('dan_preparation_seminar', 'Dan Preparation/Dan Seminar'), ('international', 'International Course'), ('family_reunion', 'Family Reunion'), ('no_registration', 'Course without Registration')], max_length=100, verbose_name='Course Type'),
        ),
    ]
