# Generated by Django 5.0.6 on 2024-11-01 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_internalcourse_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcourse',
            name='bank_transfer_until',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Bank Transfer Until'),
        ),
    ]
