# Generated by Django 5.0.6 on 2025-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_internalcourse_bank_transfer_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='session_fee',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='session_fee_cash',
        ),
        migrations.RemoveField(
            model_name='internalcourse',
            name='course_fee',
        ),
        migrations.RemoveField(
            model_name='internalcourse',
            name='course_fee_cash',
        ),
        migrations.RemoveField(
            model_name='internalcourse',
            name='course_fee_with_dan_preparation',
        ),
        migrations.RemoveField(
            model_name='internalcourse',
            name='course_fee_with_dan_preparation_cash',
        ),
        migrations.AddField(
            model_name='internalcourse',
            name='dan_discount',
            field=models.BooleanField(default=False, help_text='D.A.N. members receive a discount on this course.', verbose_name='Course with D.A.N. Member Discount'),
        ),
        migrations.AddField(
            model_name='internalcourse',
            name='fee_category',
            field=models.CharField(choices=[('regular', 'Regular Course'), ('dan_seminar', 'Dan Seminar')], default='regular_course', max_length=100, verbose_name='Fee Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcourse',
            name='has_dan_preparation',
            field=models.BooleanField(default=False, verbose_name='Course with Dan Preparation'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='course_type',
            field=models.CharField(choices=[('sensei_emmerson', 'Sensei Emmerson'), ('hombu_dojo', 'Hombu Dojo Instructor'), ('external_teacher', 'External Teacher'), ('dan_bw_teacher', 'D.A.N. BW Teacher'), ('children', 'Children')], max_length=100, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='discount_percentage',
            field=models.IntegerField(default=50, help_text='Discount for economically disadvantaged groups', verbose_name='Discount Percentage'),
        ),
    ]
