# Generated by Django 5.0.6 on 2025-02-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_coursesession_session_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcourse',
            name='has_dinner',
            field=models.BooleanField(default=False, verbose_name='Course with Dinner'),
        ),
    ]
