# Generated by Django 5.0.6 on 2025-12-07 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_internalcourse_has_dinner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesession',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Course Session', 'verbose_name_plural': 'Course Sessions'},
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='course_type',
            field=models.CharField(choices=[('sensei_emmerson', 'Sensei Emmerson'), ('hombu_dojo', 'Hombu Dojo Instructor'), ('external_teacher', 'External Teacher'), ('dan_bw_teacher', 'D.A.N. BW Teacher'), ('children', 'Children'), ('family_reunion', 'Family Reunion')], max_length=100, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='fee_category',
            field=models.CharField(choices=[('regular', 'Regular Course'), ('dan_seminar', 'Dan Seminar'), ('family_reunion', 'Family Reunion')], max_length=100, verbose_name='Fee Category'),
        ),
        migrations.CreateModel(
            name='AccommodationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'No accommodation', '2 nights', 'Full week'", max_length=200, verbose_name='Name')),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Additional fee for this accommodation option', max_digits=10, verbose_name='Fee')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_options', to='courses.internalcourse', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Accommodation Option',
                'verbose_name_plural': 'Accommodation Options',
                'ordering': ['order', 'id'],
            },
        ),
    ]
