# Generated by Django 5.0.6 on 2025-12-14 18:09
# MANUALLY FIXED to avoid parler TranslatableModel inheritance issue

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursesession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalcourse',
            options={},
        ),

        # First, create translation tables BEFORE removing fields
        migrations.CreateModel(
            name='AccommodationOptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text="e.g., 'No accommodation', '2 nights', 'Full week'", max_length=200, verbose_name='Name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.accommodationoption')),
            ],
            options={
                'verbose_name': 'Accommodation Option Translation',
                'db_table': 'courses_accommodationoption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
        ),
        migrations.CreateModel(
            name='CourseSessionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.coursesession')),
            ],
            options={
                'verbose_name': 'Course Session Translation',
                'db_table': 'courses_coursesession_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional Information')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Translation',
                'db_table': 'courses_course_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
        ),

        # Now remove the old fields
        migrations.RemoveField(
            model_name='accommodationoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='title',
        ),
        migrations.RemoveField(
            model_name='internalcourse',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='internalcourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='internalcourse',
            name='location',
        ),
    ]
