# Generated by Django 5.0.6 on 2026-03-02 13:44

import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_add_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoptiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.accommodationoption'),
        ),
        migrations.AlterField(
            model_name='coursesessiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.coursesession'),
        ),
        migrations.AlterField(
            model_name='coursetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='course_type',
            field=models.CharField(choices=[('sensei_emmerson', 'Sensei Emmerson'), ('hombu_dojo', 'Hombu Dojo Instructor'), ('external_teacher', 'External Teacher'), ('dan_bw_teacher', 'D.A.N. BW Teacher'), ('children', 'Children'), ('family_reunion', 'Family Reunion'), ('other', 'Other Course')], max_length=100, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='internalcourse',
            name='fee_category',
            field=models.CharField(choices=[('regular', 'Regular Course'), ('dan_seminar', 'Dan Seminar'), ('family_reunion', 'Family Reunion'), ('other', 'Other Course')], max_length=100, verbose_name='Fee Category'),
        ),
    ]
