# Generated by Django 5.0.6 on 2026-06-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_accommodationoptiontranslation_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, overrides the standard session fee. Cash and membership surcharges do not apply.', max_digits=6, null=True, verbose_name='Price Override'),
        ),
    ]
