# Generated by Django 5.2.14 on 2026-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursesession_price_override'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accommodationoptiontranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='coursesessiontranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='coursetranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accommodationoptiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='courses_accommodationoption_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='coursesessiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='courses_coursesession_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='coursetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='courses_course_translation_uniq_lang'),
        ),
    ]
